languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
theme ="minimal-light"

contentDir = "content"
layoutDir = "layouts"

baseURL = "https://example.com/"
Title = "Jose Rojas"

[[module.mounts]]
    source = "assets/scss"
    target = "assets/css"

[params]
col = "#433443"
avatar = "img/profile.png"
email = "jlrojas (at) utaustin.edu"
position = "MSCS Graduate Student"
affiliation = "University of Texas at Austin"
github_link = "https://github.com/J-Rojas"
linkedin = "https://linkedin.com/in/jlrojas-swdev"
cv_link = "https://drive.google.com/file/d/1kRNkdE4jRY3vqHHGX_lOkMLAsTfGUqIC/view?usp=sharing"
google_analytics = "G-NJRLFF42C7"